"""
Neurotransmitter Database — 108 neurotransmitters with complete metadata.

Exports:
    CATEGORIES       — list of 8 category display names
    CATEGORY_COLORS  — dict mapping category display name to hex color
    EFFECT_COLORS    — dict mapping postsynaptic effect to hex color
    NT_DATABASE      — list of 108 dicts, each with all required fields
"""

# ---------------------------------------------------------------------------
# Category definitions
# ---------------------------------------------------------------------------
CATEGORIES = [
    "Catecholamines",
    "Indoleamines & Trace Amines",
    "Amino Acids",
    "Acetylcholine",
    "Opioid Peptides",
    "Non-Opioid Peptides",
    "Purines",
    "Gasotransmitters & Lipids",
]

CATEGORY_COLORS = {
    "Catecholamines":              "#3b82f6",
    "Indoleamines & Trace Amines": "#c026d3",
    "Amino Acids":                 "#10b981",
    "Acetylcholine":               "#f59e0b",
    "Opioid Peptides":             "#ef4444",
    "Non-Opioid Peptides":         "#fb923c",
    "Purines":                     "#06b6d4",
    "Gasotransmitters & Lipids":   "#84cc16",
}

EFFECT_COLORS = {
    "Excitatory": "#ef4444",
    "Inhibitory": "#3b82f6",
    "Modulatory": "#a855f7",
    "Mixed":      "#eab308",
}

# ---------------------------------------------------------------------------
# Compact category lookup:  (category, category_group, color)
# ---------------------------------------------------------------------------
_CAT = {
    "CAT": ("Catecholamines",              "Monoamines",                 "#3b82f6"),
    "IND": ("Indoleamines & Trace Amines", "Monoamines",                 "#c026d3"),
    "AA":  ("Amino Acids",                 "Amino Acids",                "#10b981"),
    "ACH": ("Acetylcholine",               "Acetylcholine",              "#f59e0b"),
    "OPI": ("Opioid Peptides",             "Neuropeptides",              "#ef4444"),
    "NOP": ("Non-Opioid Peptides",         "Neuropeptides",              "#fb923c"),
    "PUR": ("Purines",                     "Purines",                    "#06b6d4"),
    "GAS": ("Gasotransmitters & Lipids",   "Gasotransmitters & Lipids",  "#84cc16"),
}


def _nt(id, name, abbr, cat_key, effect, detail, precursor, enzyme,
        location, receptors, behavior, disorders, drugs):
    """Build a single NT dict from compact args."""
    cat, grp, color = _CAT[cat_key]
    return {
        "id": id,
        "name": name,
        "abbreviation": abbr,
        "category": cat,
        "category_group": grp,
        "postsynaptic_effect": effect,
        "postsynaptic_detail": detail,
        "precursor": precursor,
        "synthesis_enzyme": enzyme,
        "primary_location": location,
        "receptor_types": receptors,
        "behavioral_role": behavior,
        "disorders": disorders,
        "drugs": drugs,
        "color": color,
    }


# ---------------------------------------------------------------------------
# NT_DATABASE  (108 entries)
# ---------------------------------------------------------------------------
NT_DATABASE = [
    # ===== CATEGORY 1: CATECHOLAMINES (IDs 1-3) =====
    _nt(1, "Dopamine", "DA", "CAT", "Mixed",
        "Excitatory via D1/D5, inhibitory via D2/D3/D4",
        "L-Tyrosine -> L-DOPA",
        "Tyrosine Hydroxylase (TH), DOPA Decarboxylase (DDC)",
        "VTA, Substantia Nigra, Hypothalamus",
        "D1, D2, D3, D4, D5 (GPCRs)",
        "Reward, motivation, motor control, executive function",
        "Parkinson's disease, Schizophrenia, ADHD, Addiction",
        "L-DOPA, Amphetamine, Methylphenidate, Antipsychotics (Haloperidol, Risperidone)"),

    _nt(2, "Norepinephrine", "NE", "CAT", "Excitatory",
        "Primarily excitatory via alpha-1 and beta adrenergic receptors",
        "Dopamine (hydroxylation via DBH)",
        "Dopamine Beta-Hydroxylase (DBH)",
        "Locus Coeruleus, Sympathetic Nerves",
        "Alpha-1, Alpha-2, Beta-1, Beta-2, Beta-3 (GPCRs)",
        "Alertness, attention, fight-or-flight arousal",
        "PTSD, Depression, Anxiety disorders, ADHD",
        "SNRIs (Venlafaxine, Duloxetine), Atomoxetine, Propranolol, Clonidine"),

    _nt(3, "Epinephrine", "Epi", "CAT", "Excitatory",
        "Excitatory via alpha and beta adrenergic receptors",
        "Norepinephrine (methylation via PNMT)",
        "Phenylethanolamine N-methyltransferase (PNMT)",
        "Adrenal Medulla, Brainstem",
        "Alpha-1, Alpha-2, Beta-1, Beta-2, Beta-3 (GPCRs)",
        "Acute stress response, cardiac stimulation",
        "Anaphylaxis, Cardiac arrest, Pheochromocytoma",
        "Epinephrine (EpiPen), Beta-blockers (Propranolol)"),

    # ===== CATEGORY 2: INDOLEAMINES & TRACE AMINES (IDs 4-11) =====
    _nt(4, "Serotonin", "5-HT", "IND", "Mixed",
        "Excitatory via 5-HT2, inhibitory via 5-HT1",
        "L-Tryptophan -> 5-HTP",
        "Tryptophan Hydroxylase (TPH1/TPH2), Aromatic L-Amino Acid Decarboxylase (AADC)",
        "Raphe Nuclei, Enteric NS, Platelets",
        "5-HT1A-F, 5-HT2A-C, 5-HT3, 5-HT4, 5-HT5-7 (GPCRs + 5-HT3 ionotropic)",
        "Mood regulation, sleep, appetite, pain perception",
        "Depression, Anxiety, OCD, Migraine, IBS",
        "SSRIs (Fluoxetine, Sertraline), Triptans, Buspirone, Ondansetron"),

    _nt(5, "Melatonin", "MT", "IND", "Modulatory",
        "Modulatory via MT1/MT2 receptors",
        "Serotonin (acetylation/methylation)",
        "Arylalkylamine N-acetyltransferase (AANAT), HIOMT",
        "Pineal Gland",
        "MT1, MT2 (GPCRs)",
        "Circadian rhythm, sleep-wake cycle",
        "Insomnia, Circadian rhythm disorders, Jet lag",
        "Melatonin supplements, Ramelteon, Tasimelteon, Agomelatine"),

    _nt(6, "Histamine", "HA", "IND", "Excitatory",
        "Excitatory via H1 and H2 receptors",
        "L-Histidine (decarboxylation via HDC)",
        "Histidine Decarboxylase (HDC)",
        "Tuberomammillary Nucleus, Hypothalamus",
        "H1, H2, H3, H4 (GPCRs)",
        "Wakefulness, appetite, immune modulation",
        "Allergies, Narcolepsy, Gastric ulcers",
        "Antihistamines (Diphenhydramine, Cetirizine), H2 blockers (Ranitidine), Pitolisant"),

    _nt(7, "Tryptamine", "Tryp", "IND", "Modulatory",
        "Modulatory via trace amine-associated receptors (TAARs) and 5-HT receptors",
        "L-Tryptophan (decarboxylation via AADC)",
        "Aromatic L-Amino Acid Decarboxylase (AADC)",
        "Brainstem, GI Tract",
        "TAAR1, 5-HT receptors (GPCRs)",
        "Neuromodulation, trace amine signaling",
        "Depression (emerging research), Migraine",
        "MAO inhibitors (indirectly increase levels)"),

    _nt(8, "Tyramine", "Tyra", "IND", "Excitatory",
        "Excitatory (indirect sympathomimetic, promotes NE release)",
        "L-Tyrosine (decarboxylation)",
        "Aromatic L-Amino Acid Decarboxylase (AADC)",
        "Sympathetic Nerve Terminals",
        "TAAR1 (GPCR)",
        "Sympathomimetic effects, blood pressure regulation",
        "Hypertensive crisis (with MAOIs), Migraine",
        "MAO inhibitors (dangerous interaction), Tyramine-restricted diet with MAOIs"),

    _nt(9, "Phenylethylamine", "PEA", "IND", "Excitatory",
        "Excitatory (indirect, promotes DA/NE release)",
        "L-Phenylalanine (decarboxylation)",
        "Aromatic L-Amino Acid Decarboxylase (AADC)",
        "Limbic System, Nigrostriatal Pathway",
        "TAAR1 (GPCR)",
        "Mood elevation, attention, runner's high",
        "ADHD, Depression",
        "Amphetamine (structural analog), Selegiline (MAO-B inhibitor increases PEA)"),

    _nt(10, "Octopamine", "Oct", "IND", "Modulatory",
        "Modulatory, modulates noradrenergic signaling",
        "Tyramine (hydroxylation)",
        "Dopamine Beta-Hydroxylase (DBH) or Tyramine Beta-Hydroxylase",
        "Sympathetic Ganglia",
        "TAAR1, Octopamine receptors (GPCRs)",
        "Modulation of noradrenergic signaling",
        "Peripheral neuropathies (emerging)",
        "Synephrine (related agonist), MAO inhibitors"),

    _nt(11, "N,N-Dimethyltryptamine", "DMT", "IND", "Modulatory",
        "Modulatory (5-HT2A agonist)",
        "Tryptamine (methylation via INMT)",
        "Indolethylamine N-methyltransferase (INMT)",
        "Pineal Gland (debated), Lungs",
        "5-HT2A, 5-HT2C, Sigma-1, TAAR1 (GPCRs)",
        "Endogenous psychedelic, consciousness modulation (debated)",
        "Psychosis (speculative), Near-death experiences",
        "Ayahuasca (contains DMT + MAOIs), DMT research compounds"),

    # ===== CATEGORY 3: AMINO ACIDS (IDs 12-20, 91, 101, 102, 107) =====
    _nt(12, "Glutamate", "Glu", "AA", "Excitatory",
        "Primary excitatory neurotransmitter via ionotropic and metabotropic receptors",
        "Alpha-Ketoglutarate (transamination) or Glutamine",
        "Glutaminase, Aminotransferases",
        "Cerebral Cortex, Hippocampus, Widespread",
        "NMDA, AMPA, Kainate (ionotropic); mGluR1-8 (metabotropic GPCRs)",
        "Primary excitatory NT, learning, memory, synaptic plasticity",
        "Epilepsy, Stroke (excitotoxicity), Alzheimer's, ALS",
        "Memantine (NMDA antagonist), Ketamine, Perampanel (AMPA antagonist), Riluzole"),

    _nt(13, "GABA", "GABA", "AA", "Inhibitory",
        "Primary inhibitory neurotransmitter via GABA-A (ionotropic) and GABA-B (metabotropic)",
        "Glutamate (via GAD enzyme)",
        "Glutamic Acid Decarboxylase (GAD65/GAD67)",
        "Cortex, Cerebellum, Basal Ganglia, Widespread",
        "GABA-A (ionotropic Cl- channel), GABA-B (GPCR), GABA-C (ionotropic)",
        "Primary inhibitory NT, anxiety reduction, muscle relaxation",
        "Epilepsy, Anxiety disorders, Insomnia, Huntington's disease",
        "Benzodiazepines (Diazepam), Barbiturates, Gabapentin, Baclofen, Vigabatrin"),

    _nt(14, "Glycine", "Gly", "AA", "Mixed",
        "Inhibitory in spinal cord; excitatory as NMDA co-agonist in brain",
        "Serine (via SHMT enzyme)",
        "Serine Hydroxymethyltransferase (SHMT)",
        "Spinal Cord, Brainstem",
        "GlyR (ionotropic Cl- channel), NMDA receptor (co-agonist site)",
        "Inhibitory signaling in spinal cord, motor control, NMDA co-agonism",
        "Hyperekplexia (startle disease), Glycine encephalopathy",
        "Strychnine (GlyR antagonist), Glycine supplements, GlyT1 inhibitors"),

    _nt(15, "D-Serine", "D-Ser", "AA", "Excitatory",
        "Excitatory as NMDA receptor co-agonist at glycine binding site",
        "L-Serine (via Serine Racemase)",
        "Serine Racemase (SRR)",
        "Hippocampus, Cortex, Astrocytes",
        "NMDA receptor (glycine co-agonist site)",
        "NMDA receptor co-agonist, synaptic plasticity, memory",
        "Schizophrenia (deficit), Alzheimer's disease, ALS",
        "D-Serine supplements, Sodium benzoate (DAAO inhibitor)"),

    _nt(16, "Aspartate", "Asp", "AA", "Excitatory",
        "Excitatory via NMDA receptor activation",
        "Oxaloacetate (transamination)",
        "Aspartate Aminotransferase (AST)",
        "Hippocampus, Cortex",
        "NMDA receptors (ionotropic)",
        "Excitatory neurotransmission, NMDA receptor activation",
        "Epilepsy, Excitotoxic neurodegeneration",
        "NMDA receptor antagonists (indirectly)"),

    _nt(17, "Taurine", "Tau", "AA", "Inhibitory",
        "Primarily inhibitory via glycine and GABA-A receptor modulation",
        "Cysteine (oxidation/decarboxylation)",
        "Cysteine Dioxygenase (CDO), Cysteine Sulfinic Acid Decarboxylase (CSAD)",
        "Cerebellum, Retina, Widespread",
        "GlyR (partial agonist), GABA-A (weak agonist), Taurine transporter (TauT)",
        "Neuromodulation, osmoregulation, neuroprotection",
        "Epilepsy (adjunctive), Cardiovascular disease, Retinal degeneration",
        "Taurine supplements, Energy drinks (taurine component)"),

    _nt(18, "Beta-Alanine", "b-Ala", "AA", "Inhibitory",
        "Inhibitory via glycine receptor agonism",
        "Pyrimidine degradation",
        "Dihydropyrimidine Dehydrogenase, Beta-ureidopropionase",
        "Spinal Cord, Muscle",
        "GlyR (glycine receptor agonist)",
        "Glycine receptor modulation, muscle endurance",
        "Hyper-beta-alaninemia, Muscle fatigue (supplementation target)",
        "Beta-Alanine supplements (athletic performance)"),

    _nt(19, "Homocysteine", "Hcy", "AA", "Excitatory",
        "Excitatory (excitotoxic at high levels via NMDA receptor)",
        "Methionine (demethylation)",
        "S-Adenosylhomocysteine Hydrolase (SAHH)",
        "Cortex, Hippocampus",
        "NMDA receptors (agonist), Group I mGluRs",
        "Excitotoxicity (pathological excess), NMDA modulation",
        "Hyperhomocysteinemia, Alzheimer's disease, Stroke, Cardiovascular disease",
        "Folate, Vitamin B12, Vitamin B6 (lower homocysteine levels)"),

    _nt(20, "D-Aspartate", "D-Asp", "AA", "Excitatory",
        "Excitatory via NMDA receptor agonism",
        "L-Aspartate (racemization)",
        "Aspartate Racemase",
        "Pineal Gland, Pituitary, Testes",
        "NMDA receptors (agonist)",
        "Neuroendocrine regulation, hormone secretion",
        "Neuroendocrine dysfunction (emerging research)",
        "D-Aspartate supplements (testosterone research)"),

    # ===== CATEGORY 4: ACETYLCHOLINE (ID 21) =====
    _nt(21, "Acetylcholine", "ACh", "ACH", "Mixed",
        "Excitatory at nicotinic receptors; mixed at muscarinic (excitatory M1/M3/M5, inhibitory M2/M4)",
        "Choline + Acetyl-CoA (via ChAT)",
        "Choline Acetyltransferase (ChAT)",
        "Basal Forebrain (Nucleus Basalis), NMJ, Striatum, PNS",
        "Nicotinic (nAChR, ionotropic); Muscarinic M1-M5 (GPCRs)",
        "Memory, attention, muscle contraction, parasympathetic function",
        "Alzheimer's disease, Myasthenia Gravis, Autonomic dysfunction",
        "Donepezil, Rivastigmine, Galantamine (AChE inhibitors), Atropine, Nicotine"),

    # ===== CATEGORY 5: OPIOID PEPTIDES (IDs 22-28) =====
    _nt(22, "Beta-Endorphin", "b-End", "OPI", "Inhibitory",
        "Inhibitory via mu-opioid receptors coupled to Gi proteins",
        "Pro-opiomelanocortin (POMC)",
        "Prohormone Convertases (PC1/PC3)",
        "Hypothalamus (Arcuate Nucleus), Pituitary",
        "Mu-opioid receptor (MOR, GPCR)",
        "Pain relief, euphoria, stress response",
        "Chronic pain, Addiction, Stress-related disorders",
        "Naloxone (MOR antagonist), Morphine (MOR agonist)"),

    _nt(23, "Met-Enkephalin", "Met-Enk", "OPI", "Inhibitory",
        "Inhibitory via delta-opioid receptor agonism",
        "Proenkephalin",
        "Prohormone Convertases",
        "Adrenal Medulla, Striatum, Spinal Cord",
        "Delta-opioid receptor (DOR, GPCR), Mu-opioid receptor (MOR)",
        "Pain modulation, reward processing",
        "Chronic pain, Opioid addiction",
        "Enkephalinase inhibitors (Racecadotril), DOR agonists"),

    _nt(24, "Leu-Enkephalin", "Leu-Enk", "OPI", "Inhibitory",
        "Inhibitory via delta-opioid receptor agonism",
        "Proenkephalin",
        "Prohormone Convertases",
        "Striatum, Hippocampus, PAG",
        "Delta-opioid receptor (DOR, GPCR)",
        "Analgesia, emotional regulation",
        "Chronic pain, Mood disorders",
        "DOR agonists, Enkephalinase inhibitors"),

    _nt(25, "Dynorphin", "Dyn", "OPI", "Inhibitory",
        "Inhibitory via kappa-opioid receptor agonism",
        "Prodynorphin",
        "Prohormone Convertases",
        "Hypothalamus, Hippocampus, Spinal Cord",
        "Kappa-opioid receptor (KOR, GPCR)",
        "Pain processing, dysphoria, stress response",
        "Depression, Addiction, Chronic pain, Dysphoria",
        "KOR antagonists (Buprenorphine partial, JDTic), Salvinorin A (KOR agonist)"),

    _nt(26, "Endomorphin-1", "EM-1", "OPI", "Inhibitory",
        "Inhibitory via mu-opioid receptor agonism (high affinity)",
        "Unknown precursor (putative)",
        "Unknown (putative enzymatic synthesis)",
        "Thalamus, Cortex, Amygdala",
        "Mu-opioid receptor (MOR, GPCR, high affinity)",
        "High-affinity mu-opioid agonist, potent analgesia",
        "Chronic pain, Opioid tolerance",
        "MOR agonists (Morphine), Naloxone (antagonist)"),

    _nt(27, "Endomorphin-2", "EM-2", "OPI", "Inhibitory",
        "Inhibitory via mu-opioid receptor agonism",
        "Unknown precursor (putative)",
        "Unknown (putative enzymatic synthesis)",
        "Spinal Cord, Hypothalamus",
        "Mu-opioid receptor (MOR, GPCR)",
        "Pain modulation, reward, autonomic regulation",
        "Chronic pain, Autonomic dysfunction",
        "MOR agonists, Naloxone (antagonist)"),

    _nt(28, "Nociceptin", "N/OFQ", "OPI", "Inhibitory",
        "Inhibitory via NOP receptor coupled to Gi proteins",
        "Prepronociceptin",
        "Prohormone Convertases",
        "Cortex, Hippocampus, Amygdala",
        "NOP receptor (Nociceptin/Orphanin FQ receptor, GPCR)",
        "Pain processing, anxiety, learning",
        "Anxiety disorders, Pain syndromes, Drug addiction",
        "NOP receptor antagonists (JTC-801), Cebranopadol (NOP/MOR agonist)"),

    # ===== CATEGORY 6: NON-OPIOID PEPTIDES (IDs 29-74, 95-100, 103-106, 108) =====
    _nt(29, "Substance P", "SP", "NOP", "Excitatory",
        "Excitatory via NK1 receptor",
        "Preprotachykinin A (PPT-A)",
        "Preprotachykinin A gene processing, Prohormone Convertases",
        "Dorsal Horn, Substantia Nigra, Hypothalamus",
        "NK1 receptor (Neurokinin-1, GPCR)",
        "Pain transmission (nociception), inflammation, mood",
        "Chronic pain, Depression, Inflammatory bowel disease",
        "Aprepitant (NK1 antagonist), Fosaprepitant"),

    _nt(30, "Neurokinin A", "NKA", "NOP", "Excitatory",
        "Excitatory via NK2 receptor",
        "Preprotachykinin A (PPT-A)",
        "Preprotachykinin A gene processing",
        "Spinal Cord, GI Tract",
        "NK2 receptor (Neurokinin-2, GPCR)",
        "Smooth muscle contraction, pain, airway regulation",
        "Asthma, Chronic pain, GI motility disorders",
        "NK2 receptor antagonists (Saredutant)"),

    _nt(31, "Neurokinin B", "NKB", "NOP", "Excitatory",
        "Excitatory via NK3 receptor",
        "Preprotachykinin B (PPT-B)",
        "Preprotachykinin B gene processing",
        "Hypothalamus, Placenta",
        "NK3 receptor (Neurokinin-3, GPCR)",
        "Reproductive regulation (GnRH pulsatility)",
        "Hypogonadotropic hypogonadism, Preeclampsia, Menopausal hot flashes",
        "NK3 receptor antagonists (Fezolinetant, Pavinetant)"),

    _nt(32, "Oxytocin", "OT", "NOP", "Modulatory",
        "Modulatory via oxytocin receptor (Gq-coupled)",
        "Preprooxytocin",
        "Peptidylglycine Alpha-Amidating Monooxygenase (PAM), Prohormone Convertases",
        "Hypothalamus (PVN, SON)",
        "Oxytocin receptor (OXTR, GPCR Gq-coupled)",
        "Social bonding, trust, parturition, lactation",
        "Autism spectrum disorder, Social anxiety, Postpartum hemorrhage",
        "Pitocin (synthetic oxytocin), Carbetocin, Atosiban (OT antagonist)"),

    _nt(33, "Vasopressin", "AVP", "NOP", "Modulatory",
        "Modulatory via V1a, V1b, and V2 receptors",
        "Prepropressophysin",
        "Prohormone Convertases",
        "Hypothalamus (PVN, SON)",
        "V1a (Gq), V1b (Gq), V2 (Gs) (GPCRs)",
        "Water retention, blood pressure, social behavior, aggression",
        "Diabetes insipidus, SIADH, Enuresis",
        "Desmopressin (V2 agonist), Conivaptan (V1a/V2 antagonist), Tolvaptan"),

    _nt(34, "Neuropeptide Y", "NPY", "NOP", "Inhibitory",
        "Inhibitory via Y1/Y2 receptors coupled to Gi proteins",
        "Pre-pro-NPY",
        "Prohormone Convertases, Signal Peptidase",
        "Hypothalamus (Arcuate), Locus Coeruleus, Cortex",
        "Y1, Y2, Y4, Y5 (GPCRs, Gi-coupled)",
        "Appetite stimulation, stress resilience, anxiolysis",
        "Obesity, Anxiety disorders, Epilepsy, PTSD",
        "Y1 antagonists (BIBO 3304), Y5 antagonists (Velneperit)"),

    _nt(35, "Corticotropin-Releasing Hormone", "CRH", "NOP", "Excitatory",
        "Excitatory via CRH-R1 coupled to Gs",
        "Pre-pro-CRH",
        "Prohormone Convertases",
        "Hypothalamus (PVN), Amygdala",
        "CRH-R1 (Gs), CRH-R2 (Gs) (GPCRs)",
        "Stress response (HPA axis activation), anxiety, arousal",
        "Depression, Anxiety, Cushing's disease, PTSD",
        "CRH-R1 antagonists (Antalarmin, Pexacerfont)"),

    _nt(36, "Thyrotropin-Releasing Hormone", "TRH", "NOP", "Excitatory",
        "Excitatory via TRH receptor (Gq-coupled)",
        "Pre-pro-TRH",
        "Prohormone Convertases, Pyroglutamyl Peptidase",
        "Hypothalamus, Brainstem",
        "TRH-R1, TRH-R2 (GPCRs, Gq-coupled)",
        "Thyroid regulation, arousal, antidepressant effects",
        "Hypothyroidism, Depression (adjunctive), Spinocerebellar ataxia",
        "Protirelin (TRH analog), Taltirelin"),

    _nt(37, "Gonadotropin-Releasing Hormone", "GnRH", "NOP", "Excitatory",
        "Excitatory via GnRH receptor (Gq-coupled)",
        "Pre-pro-GnRH",
        "Prohormone Convertases",
        "Hypothalamus (Preoptic Area)",
        "GnRH receptor (GnRHR, GPCR Gq-coupled)",
        "Reproductive behavior, puberty onset, LH/FSH release",
        "Precocious puberty, Hypogonadism, Endometriosis, Prostate cancer",
        "Leuprolide, Goserelin (GnRH agonists), Cetrorelix (GnRH antagonist)"),

    _nt(38, "Somatostatin", "SST", "NOP", "Inhibitory",
        "Inhibitory via SSTRs coupled to Gi proteins",
        "Preprosomatostatin",
        "Prohormone Convertases",
        "Hypothalamus, Cortex, GI Tract",
        "SSTR1-5 (GPCRs, Gi-coupled)",
        "Inhibition of growth hormone, neuromodulation, GI regulation",
        "Acromegaly, Neuroendocrine tumors, Gastroparesis",
        "Octreotide, Lanreotide (SST analogs), Pasireotide"),

    _nt(39, "Cholecystokinin", "CCK", "NOP", "Excitatory",
        "Excitatory via CCK-A and CCK-B receptors",
        "Pre-pro-CCK",
        "Prohormone Convertases",
        "Cortex, Hippocampus, GI Tract",
        "CCK-A (CCK1R), CCK-B (CCK2R) (GPCRs, Gq-coupled)",
        "Satiety signaling, anxiety/panic, memory modulation",
        "Panic disorder, Obesity, Schizophrenia (CCK-DA interactions)",
        "CCK-B antagonists (CI-988, L-365260), Sincalide (CCK-A agonist)"),

    _nt(40, "Vasoactive Intestinal Peptide", "VIP", "NOP", "Excitatory",
        "Excitatory via VPAC1/VPAC2 coupled to Gs",
        "Pre-pro-VIP",
        "Prohormone Convertases",
        "Hypothalamus (SCN), Cortex, GI Tract",
        "VPAC1, VPAC2 (GPCRs, Gs-coupled)",
        "Circadian rhythm, vasodilation, neuroprotection",
        "Pulmonary hypertension, GI motility disorders, Migraine",
        "VIP analogs (Aviptadil), VPAC2 agonists"),

    _nt(41, "Pituitary Adenylate Cyclase-Activating Peptide", "PACAP", "NOP", "Excitatory",
        "Excitatory via PAC1 receptor coupled to Gs",
        "Pre-pro-PACAP",
        "Prohormone Convertases",
        "Hypothalamus, Adrenal, PNS",
        "PAC1 (Gs), VPAC1, VPAC2 (GPCRs)",
        "Stress response, neuroprotection, neurodevelopment",
        "PTSD, Migraine, Neurodegenerative diseases",
        "PAC1 receptor antagonists (experimental), PACAP38 analogs"),

    _nt(42, "Galanin", "GAL", "NOP", "Mixed",
        "Inhibitory via GalR1 (Gi), excitatory via GalR2 (Gq)",
        "Pre-pro-Galanin",
        "Prohormone Convertases",
        "Hypothalamus, Locus Coeruleus, Basal Forebrain",
        "GalR1 (Gi), GalR2 (Gq), GalR3 (Gi) (GPCRs)",
        "Feeding, pain modulation, mood, cognition",
        "Depression, Epilepsy, Alzheimer's disease, Chronic pain",
        "Galanin analogs (Galmic, NAX 5055), GalR2 agonists"),

    _nt(43, "Neurotensin", "NTS", "NOP", "Excitatory",
        "Excitatory via NTS1 receptor; also modulatory",
        "Pre-pro-Neurotensin",
        "Prohormone Convertases",
        "VTA, Hypothalamus, Amygdala",
        "NTS1 (Gq), NTS2 (Gq), NTS3/Sortilin (GPCRs)",
        "Dopamine modulation, pain regulation, thermoregulation",
        "Schizophrenia, Pain disorders, Obesity",
        "NTS1 agonists (PD149163), NTS1 antagonists (SR 48692)"),

    _nt(44, "Orexin-A", "OX-A", "NOP", "Excitatory",
        "Excitatory via OX1R/OX2R coupled to Gq",
        "Prepro-orexin",
        "Prohormone Convertases",
        "Lateral Hypothalamus",
        "OX1R (Gq), OX2R (Gq) (GPCRs)",
        "Wakefulness, appetite, arousal, reward-seeking",
        "Narcolepsy type 1, Insomnia, Addiction",
        "Suvorexant, Lemborexant (Dual OXR antagonists), OX2R agonists (TAK-994)"),

    _nt(45, "Orexin-B", "OX-B", "NOP", "Excitatory",
        "Excitatory via OX2R coupled to Gq",
        "Prepro-orexin",
        "Prohormone Convertases",
        "Lateral Hypothalamus",
        "OX2R (Gq, preferential) (GPCR)",
        "Sleep-wake regulation, energy homeostasis",
        "Narcolepsy, Hypersomnia",
        "Suvorexant, Lemborexant (OXR antagonists)"),

    _nt(46, "Calcitonin Gene-Related Peptide", "CGRP", "NOP", "Excitatory",
        "Excitatory via CLR/RAMP1 complex coupled to Gs",
        "CALCA Gene (alternative splicing)",
        "Alternative mRNA splicing of Calcitonin gene",
        "Trigeminal Ganglion, Dorsal Horn, Cerebellum",
        "CLR/RAMP1 (CGRP receptor, Gs), CLR/RAMP3 (GPCRs)",
        "Migraine pathogenesis, vasodilation, pain signaling",
        "Migraine, Cluster headache, Trigeminal neuralgia",
        "Erenumab, Galcanezumab, Fremanezumab (anti-CGRP mAbs), Rimegepant, Ubrogepant"),

    _nt(47, "Adrenocorticotropic Hormone", "ACTH", "NOP", "Modulatory",
        "Modulatory via melanocortin receptors (MC2R)",
        "POMC (same precursor as beta-endorphin)",
        "Prohormone Convertases (PC1/PC3)",
        "Anterior Pituitary, Hypothalamus",
        "MC2R (Gs-coupled GPCR, adrenal cortex)",
        "Cortisol release, stress response",
        "Cushing's disease, Addison's disease, Infantile spasms",
        "Cosyntropin (synthetic ACTH), Ketoconazole (cortisol synthesis inhibitor)"),

    _nt(48, "Alpha-Melanocyte-Stimulating Hormone", "a-MSH", "NOP", "Modulatory",
        "Modulatory via MC3R/MC4R",
        "POMC",
        "Prohormone Convertases (PC1/PC3, PC2)",
        "Hypothalamus (Arcuate Nucleus)",
        "MC3R, MC4R, MC1R (GPCRs, Gs-coupled)",
        "Appetite suppression, skin pigmentation, anti-inflammatory",
        "Obesity (MC4R mutations), Skin pigmentation disorders",
        "Setmelanotide (MC4R agonist), Afamelanotide (MC1R agonist)"),

    _nt(49, "Agouti-Related Peptide", "AgRP", "NOP", "Inhibitory",
        "Inhibitory (MC3R/MC4R inverse agonist)",
        "Pre-pro-AgRP",
        "Prohormone Convertases",
        "Hypothalamus (Arcuate Nucleus)",
        "MC3R, MC4R (inverse agonist/antagonist) (GPCRs)",
        "Appetite stimulation, energy homeostasis (antagonizes alpha-MSH)",
        "Obesity, Cachexia, Anorexia nervosa",
        "MC4R agonists (antagonize AgRP effects), Setmelanotide"),

    _nt(50, "CART", "CART", "NOP", "Modulatory",
        "Modulatory (receptor not fully identified; putative GPCR signaling)",
        "Pre-pro-CART",
        "Prohormone Convertases",
        "Hypothalamus (Arcuate), VTA, Nucleus Accumbens",
        "Putative CART receptor (not yet cloned, GPCR suspected)",
        "Appetite suppression, reward, stress",
        "Obesity, Addiction, Depression",
        "Cocaine, Amphetamine (induce CART expression)"),

    _nt(51, "Neuropeptide S", "NPS", "NOP", "Excitatory",
        "Excitatory via NPSR coupled to Gq/Gs",
        "Pre-pro-NPS",
        "Signal Peptidase, Prohormone Convertases",
        "Brainstem (Locus Coeruleus area)",
        "NPSR (NPS receptor, GPCR Gq/Gs-coupled)",
        "Arousal, anxiolysis, wakefulness",
        "Anxiety disorders, Sleep disorders, Asthma",
        "NPSR agonists (SHA 68 antagonist in research)"),

    _nt(52, "Neuropeptide B", "NPB", "NOP", "Modulatory",
        "Modulatory via NPBWR1/R2 receptors",
        "Pre-pro-NPB",
        "Prohormone Convertases",
        "Hypothalamus, Amygdala",
        "NPBWR1 (GPR7), NPBWR2 (GPR8) (GPCRs, Gi-coupled)",
        "Pain modulation, feeding, neuroendocrine regulation",
        "Obesity, Pain disorders, Neuroendocrine dysregulation",
        "NPBWR1/R2 agonists (experimental)"),

    _nt(53, "Neuropeptide W", "NPW", "NOP", "Modulatory",
        "Modulatory via NPBWR1/R2 receptors",
        "Pre-pro-NPW",
        "Prohormone Convertases",
        "Hypothalamus, Brainstem",
        "NPBWR1 (GPR7), NPBWR2 (GPR8) (GPCRs, Gi-coupled)",
        "Energy homeostasis, neuroendocrine regulation, stress",
        "Obesity, Stress disorders, Metabolic syndrome",
        "NPBWR1/R2 ligands (experimental)"),

    _nt(54, "Prolactin-Releasing Peptide", "PrRP", "NOP", "Modulatory",
        "Modulatory via GPR10 receptor",
        "Pre-pro-PrRP",
        "Prohormone Convertases",
        "Brainstem (NTS, DMH)",
        "GPR10 (GPCR)",
        "Stress response, food intake, prolactin regulation",
        "Obesity, Stress disorders, Hyperprolactinemia",
        "GPR10 agonists (experimental), PrRP analogs"),

    _nt(55, "Kisspeptin", "KISS1", "NOP", "Excitatory",
        "Excitatory via KISS1R / GPR54 coupled to Gq",
        "KISS1 Gene",
        "KISS1 gene product processing by Furin, Prohormone Convertases",
        "Hypothalamus (Arcuate, AVPV)",
        "KISS1R / GPR54 (GPCR, Gq-coupled)",
        "Puberty onset, GnRH regulation, reproductive behavior",
        "Hypogonadotropic hypogonadism, Precocious puberty, Infertility",
        "Kisspeptin-54 (research), Kisspeptin analogs (MVT-602)"),

    _nt(56, "Ghrelin", "GHRL", "NOP", "Excitatory",
        "Excitatory via GHSR1a coupled to Gq",
        "Preproghrelin",
        "Ghrelin O-acyltransferase (GOAT), Prohormone Convertases",
        "Stomach, Hypothalamus (Arcuate)",
        "GHSR1a (Growth Hormone Secretagogue Receptor, GPCR Gq-coupled)",
        "Hunger signaling, growth hormone release, reward-driven eating",
        "Obesity, Anorexia nervosa, Cachexia, Growth hormone deficiency",
        "GHSR antagonists (experimental), Anamorelin (GHSR agonist), Growth hormone secretagogues"),

    _nt(57, "Neuromedin U", "NMU", "NOP", "Excitatory",
        "Excitatory via NMUR1/NMUR2 coupled to Gq",
        "Pre-pro-NMU",
        "Prohormone Convertases",
        "Hypothalamus, GI Tract, Spinal Cord",
        "NMUR1 (Gq), NMUR2 (Gq) (GPCRs)",
        "Appetite suppression, stress, smooth muscle contraction",
        "Obesity, Inflammatory diseases, GI disorders",
        "NMUR2 agonists (experimental)"),

    _nt(58, "Neuromedin B", "NMB", "NOP", "Excitatory",
        "Excitatory via NMBR coupled to Gq",
        "Pre-pro-NMB",
        "Prohormone Convertases",
        "GI Tract, Hypothalamus, Brainstem",
        "NMBR (Neuromedin B receptor, GPCR Gq-coupled)",
        "Satiety, thermoregulation, smooth muscle tone",
        "Cancer (ectopic production), Obesity",
        "NMBR antagonists (PD 168368, experimental)"),

    _nt(59, "Gastrin-Releasing Peptide", "GRP", "NOP", "Excitatory",
        "Excitatory via GRPR coupled to Gq",
        "Pre-pro-GRP",
        "Prohormone Convertases",
        "GI Tract, Brainstem, Amygdala",
        "GRPR (Gastrin-releasing peptide receptor, GPCR Gq-coupled)",
        "Feeding behavior, itch sensation, memory, circadian rhythm",
        "Small cell lung cancer, Pruritus, GI disorders",
        "GRPR antagonists (RC-3095), Bombesin analogs"),

    _nt(60, "Bombesin", "BBS", "NOP", "Excitatory",
        "Excitatory via BB receptors (BB1/BB2/BB3)",
        "Pre-pro-GRP (mammalian homolog = GRP)",
        "Prohormone Convertases",
        "Brainstem, GI Tract",
        "BB1 (NMBR), BB2 (GRPR), BB3 (BRS-3) (GPCRs)",
        "Satiety, thermoregulation, arousal",
        "Cancer (tumor growth marker), Obesity",
        "Bombesin analogs, BB receptor antagonists"),

    _nt(61, "Angiotensin II", "Ang II", "NOP", "Excitatory",
        "Excitatory via AT1R coupled to Gq",
        "Angiotensinogen (via renin/ACE)",
        "Renin, Angiotensin-Converting Enzyme (ACE)",
        "Circumventricular Organs, Hypothalamus",
        "AT1R (Gq), AT2R (Gi) (GPCRs)",
        "Thirst, salt appetite, blood pressure, sympathetic activation",
        "Hypertension, Heart failure, Diabetic nephropathy",
        "ACE inhibitors (Lisinopril, Enalapril), ARBs (Losartan, Valsartan)"),

    _nt(62, "Bradykinin", "BK", "NOP", "Excitatory",
        "Excitatory via B1/B2 receptors coupled to Gq",
        "Kininogen (via kallikrein)",
        "Kallikrein (tissue and plasma forms)",
        "Peripheral Nerves, Dorsal Horn",
        "B1 (inducible, Gq), B2 (constitutive, Gq) (GPCRs)",
        "Pain signaling, inflammation, vasodilation",
        "Angioedema (hereditary), Inflammatory pain, ACE inhibitor cough",
        "Icatibant (B2 antagonist), ACE inhibitors (increase BK), Ecallantide"),

    _nt(63, "Atrial Natriuretic Peptide", "ANP", "NOP", "Inhibitory",
        "Inhibitory via NPR-A coupled to cGMP production",
        "Pre-pro-ANP",
        "Corin (atrial protease), Prohormone Convertases",
        "Hypothalamus, Atrial Cardiomyocytes",
        "NPR-A (guanylyl cyclase receptor), NPR-C (clearance receptor)",
        "Blood pressure reduction, fluid balance, anxiety modulation",
        "Heart failure, Hypertension, Edema",
        "Nesiritide (BNP analog), Sacubitril (neprilysin inhibitor, prevents ANP breakdown)"),

    _nt(64, "Brain Natriuretic Peptide", "BNP", "NOP", "Inhibitory",
        "Inhibitory via NPR-A coupled to cGMP production",
        "Pre-pro-BNP",
        "Corin, Furin, Prohormone Convertases",
        "Hypothalamus, Heart",
        "NPR-A (guanylyl cyclase receptor), NPR-C (clearance receptor)",
        "Fluid homeostasis, cardioprotection",
        "Heart failure (diagnostic biomarker), Hypertension",
        "Nesiritide (recombinant BNP), Sacubitril/Valsartan (Entresto)"),

    _nt(65, "Endothelin-1", "ET-1", "NOP", "Excitatory",
        "Excitatory via ETA receptor coupled to Gq",
        "Pre-pro-Endothelin-1",
        "Endothelin-Converting Enzyme (ECE-1)",
        "Cerebral Vasculature, Brainstem",
        "ETA (Gq), ETB (Gi/Gq) (GPCRs)",
        "Vasoconstriction, pain, cerebral blood flow regulation",
        "Pulmonary arterial hypertension, Cerebral vasospasm, Raynaud's phenomenon",
        "Bosentan, Ambrisentan (ETA antagonists), Macitentan"),

    _nt(66, "Urocortin 1", "Ucn1", "NOP", "Excitatory",
        "Excitatory via CRH-R1/R2 coupled to Gs",
        "Pre-pro-Urocortin 1",
        "Prohormone Convertases",
        "Edinger-Westphal Nucleus, Hypothalamus",
        "CRH-R1 (Gs), CRH-R2 (Gs) (GPCRs)",
        "Stress adaptation, appetite suppression, cardiovascular regulation",
        "Anxiety, Heart failure, Stress-related disorders",
        "CRH-R1 antagonists (Antalarmin), CRH-R2 selective ligands"),

    _nt(67, "Urocortin 2", "Ucn2", "NOP", "Modulatory",
        "Modulatory via CRH-R2 selective coupling to Gs",
        "Pre-pro-Urocortin 2",
        "Prohormone Convertases",
        "Hypothalamus (PVN)",
        "CRH-R2 (Gs-coupled, selective) (GPCR)",
        "Stress response, cardiovascular modulation",
        "Heart failure, Hypertension, Stress disorders",
        "CRH-R2 agonists (experimental), Astressin-2B (CRH-R2 antagonist)"),

    _nt(68, "Urocortin 3", "Ucn3", "NOP", "Modulatory",
        "Modulatory via CRH-R2 selective coupling to Gs",
        "Pre-pro-Urocortin 3",
        "Prohormone Convertases",
        "Amygdala, Hypothalamus",
        "CRH-R2 (Gs-coupled, selective) (GPCR)",
        "Stress coping, anxiolysis, social behavior",
        "Anxiety disorders, Social dysfunction, Metabolic syndrome",
        "CRH-R2 agonists (experimental)"),

    _nt(69, "Melanin-Concentrating Hormone", "MCH", "NOP", "Inhibitory",
        "Inhibitory via MCHR1 coupled to Gi",
        "Pre-pro-MCH",
        "Prohormone Convertases",
        "Lateral Hypothalamus",
        "MCHR1 (Gi-coupled GPCR), MCHR2 (Gq, not in rodents)",
        "Sleep promotion, appetite, energy balance",
        "Obesity, Narcolepsy, Depression",
        "MCHR1 antagonists (SNAP-7941, GW803430, experimental)"),

    _nt(70, "Relaxin-3", "RLN3", "NOP", "Modulatory",
        "Modulatory via RXFP3 coupled to Gi",
        "Pre-pro-Relaxin-3",
        "Prohormone Convertases",
        "Nucleus Incertus (Brainstem)",
        "RXFP3 (Gi-coupled GPCR), RXFP1",
        "Arousal, stress, feeding, memory",
        "Anxiety, Obesity, Cognitive disorders",
        "RXFP3 agonists/antagonists (experimental)"),

    _nt(71, "Secretin", "SCT", "NOP", "Excitatory",
        "Excitatory via SCTR coupled to Gs",
        "Pre-pro-Secretin",
        "Prohormone Convertases",
        "GI Tract, Hypothalamus, Cerebellum",
        "SCTR (Secretin receptor, Gs-coupled GPCR)",
        "GI regulation, water homeostasis, social behavior (emerging)",
        "Pancreatic insufficiency, Autism (research), Gastrinoma diagnosis",
        "Synthetic secretin (ChiRhoStim), Secretin stimulation test"),

    _nt(72, "Glucagon-Like Peptide-1", "GLP-1", "NOP", "Excitatory",
        "Excitatory via GLP-1R coupled to Gs",
        "Proglucagon",
        "Prohormone Convertases (PC1/PC3)",
        "NTS (Brainstem), GI Tract",
        "GLP-1R (Gs-coupled GPCR)",
        "Satiety, insulin secretion, neuroprotection",
        "Type 2 Diabetes, Obesity, Neurodegenerative diseases",
        "Semaglutide, Liraglutide, Exenatide, Tirzepatide (GLP-1R agonists), Sitagliptin (DPP-4 inhibitor)"),

    _nt(73, "Cortistatin", "CST", "NOP", "Inhibitory",
        "Inhibitory via SSTRs coupled to Gi, plus unique cortistatin receptor",
        "Pre-pro-Cortistatin",
        "Prohormone Convertases",
        "Cortex, Hippocampus",
        "SSTR1-5 (Gi-coupled), MrgX2 (cortistatin-selective) (GPCRs)",
        "Sleep induction, anti-inflammatory, somatostatin-like inhibition",
        "Insomnia, Inflammatory disorders, Acromegaly",
        "Cortistatin analogs, Somatostatin analogs (cross-react)"),

    _nt(74, "Apelin", "APLN", "NOP", "Modulatory",
        "Modulatory via APJ receptor coupled to Gi",
        "Pre-pro-Apelin",
        "Prohormone Convertases, ACE2",
        "Hypothalamus, Cardiovascular System",
        "APJ / Apelin receptor (Gi-coupled GPCR)",
        "Fluid homeostasis, cardiovascular regulation, appetite",
        "Heart failure, Hypertension, Preeclampsia",
        "Apelin analogs (experimental), APJ agonists (MM07, BMS-986224)"),

    # ===== CATEGORY 7: PURINES (IDs 75-79) =====
    _nt(75, "Adenosine Triphosphate", "ATP", "PUR", "Excitatory",
        "Excitatory via P2X receptors (ionotropic ligand-gated ion channels)",
        "Cellular Metabolism (Glycolysis, OXPHOS)",
        "ATP Synthase (mitochondrial), Glycolytic enzymes",
        "Widespread (Co-released with many NTs), Dorsal Horn",
        "P2X1-7 (ionotropic), P2Y1/2/4/6/11-14 (metabotropic GPCRs)",
        "Fast excitatory signaling, pain, inflammation",
        "Chronic pain, Migraine, Inflammatory diseases, Thrombosis",
        "Suramin (P2 antagonist), Clopidogrel (P2Y12 antagonist), A-317491 (P2X3 antagonist)"),

    _nt(76, "Adenosine", "Ado", "PUR", "Mixed",
        "Inhibitory via A1 receptor, excitatory via A2A receptor",
        "ATP Dephosphorylation (via ectonucleotidases)",
        "Ecto-5'-nucleotidase (CD73), Adenosine kinase",
        "Widespread (Basal Forebrain, Cortex)",
        "A1 (Gi), A2A (Gs), A2B (Gs), A3 (Gi) (GPCRs)",
        "Sleep pressure, neuroprotection, vasodilation (caffeine antagonizes A1/A2A)",
        "Insomnia, Parkinson's disease, Cardiac arrhythmias",
        "Caffeine (A1/A2A antagonist), Istradefylline (A2A antagonist), Regadenoson (A2A agonist)"),

    _nt(77, "Guanosine Triphosphate", "GTP", "PUR", "Modulatory",
        "Modulatory (intracellular G-protein signaling cofactor)",
        "Purine Biosynthesis",
        "IMP Dehydrogenase (IMPDH), GMP Synthetase",
        "Widespread (intracellular signaling)",
        "G-protein alpha subunits (intracellular), Tubulin GTPase",
        "G-protein signaling cascade, neuromodulation",
        "Cancer (purine metabolism target), Immunosuppression",
        "Mycophenolate (IMPDH inhibitor), Non-hydrolyzable GTP analogs (research)"),

    _nt(78, "Uridine Triphosphate", "UTP", "PUR", "Excitatory",
        "Excitatory via P2Y2/P2Y4 receptors",
        "Pyrimidine Metabolism",
        "UMP Kinase, Nucleoside Diphosphate Kinase",
        "Glia, Sensory Neurons",
        "P2Y2 (Gq), P2Y4 (Gq) (GPCRs)",
        "Glial signaling, nociception",
        "Cystic fibrosis (mucociliary clearance), Dry eye",
        "Diquafosol (P2Y2 agonist), Denufosol"),

    _nt(79, "NAD+", "NAD+", "PUR", "Modulatory",
        "Modulatory via CD38/CD157 mediated Ca2+ signaling",
        "Tryptophan / Niacin (Vitamin B3)",
        "Nicotinamide Phosphoribosyltransferase (NAMPT), NAD+ Synthase",
        "Widespread (Neurons, Glia)",
        "CD38, CD157 (ectoenzymes), P2Y11, TRPM2 (Ca2+ channel)",
        "Neuromodulation, calcium signaling, neuroprotection",
        "Aging, Neurodegeneration, Metabolic disorders",
        "Nicotinamide Riboside (NR), NMN (NAD+ precursors), CD38 inhibitors (78c)"),

    # ===== CATEGORY 8: GASOTRANSMITTERS & LIPIDS (IDs 80-90, 92-94) =====
    _nt(80, "Nitric Oxide", "NO", "GAS", "Modulatory",
        "Modulatory (retrograde messenger activating sGC to produce cGMP)",
        "L-Arginine (via NOS enzyme)",
        "Nitric Oxide Synthase (nNOS, eNOS, iNOS)",
        "Cerebellum, Hippocampus, Endothelium",
        "Soluble guanylyl cyclase (sGC, produces cGMP), S-nitrosylation targets",
        "Vasodilation, synaptic plasticity (LTP), retrograde signaling",
        "Erectile dysfunction, Pulmonary hypertension, Stroke",
        "Sildenafil, Tadalafil (PDE5 inhibitors, boost cGMP), Nitroglycerin (NO donor), L-NAME (NOS inhibitor)"),

    _nt(81, "Carbon Monoxide", "CO", "GAS", "Modulatory",
        "Modulatory (activates sGC to produce cGMP, similar to NO)",
        "Heme degradation (via Heme Oxygenase)",
        "Heme Oxygenase-1 (HO-1, inducible), Heme Oxygenase-2 (HO-2, constitutive)",
        "Hippocampus, Cerebellum, Olfactory Neurons",
        "Soluble guanylyl cyclase (sGC), BK Ca2+ channels",
        "Neuromodulation, anti-inflammatory, smooth muscle relaxation",
        "Carbon monoxide poisoning, Neurodegenerative diseases (HO role)",
        "CORM compounds (CO-releasing molecules, experimental), HO-1 inducers"),

    _nt(82, "Hydrogen Sulfide", "H2S", "GAS", "Modulatory",
        "Modulatory (modulates ion channels, NMDA receptors, KATP channels)",
        "L-Cysteine (via CBS/CSE enzymes)",
        "Cystathionine Beta-Synthase (CBS), Cystathionine Gamma-Lyase (CSE), 3-MST",
        "Hippocampus, Cortex, Cerebellum",
        "NMDA receptors (enhancer), KATP channels (opener), TRPA1",
        "Synaptic modulation, neuroprotection, vasodilation",
        "Hypertension, Neurodegenerative diseases, Inflammatory conditions",
        "NaHS, GYY4137 (H2S donors), AOAA (CBS inhibitor), PAG (CSE inhibitor)"),

    _nt(83, "Anandamide", "AEA", "GAS", "Inhibitory",
        "Inhibitory (retrograde, CB1 inhibits presynaptic neurotransmitter release)",
        "Arachidonic Acid + Ethanolamine (via NAPE-PLD)",
        "N-acyl phosphatidylethanolamine phospholipase D (NAPE-PLD)",
        "Hippocampus, Cortex, Basal Ganglia",
        "CB1 (Gi-coupled GPCR), CB2 (Gi), TRPV1 (ion channel), PPARgamma",
        "Endocannabinoid: mood, pain, appetite",
        "Chronic pain, Anxiety, Depression, Obesity",
        "FAAH inhibitors (PF-04457845, URB597), THC (CB1 agonist), Rimonabant (CB1 antagonist)"),

    _nt(84, "2-Arachidonoylglycerol", "2-AG", "GAS", "Inhibitory",
        "Inhibitory (retrograde, CB1 inhibits presynaptic release)",
        "Diacylglycerol (via DAG Lipase)",
        "Diacylglycerol Lipase alpha/beta (DAGLa/DAGLb)",
        "Widespread (Cortex, Hippocampus, Cerebellum)",
        "CB1 (Gi-coupled GPCR), CB2 (Gi)",
        "Endocannabinoid: retrograde synaptic signaling, immune modulation",
        "Epilepsy, Multiple sclerosis, Neuroinflammation",
        "MAGL inhibitors (JZL184, ABX-1431), THC (CB1 agonist), CBD (indirect modulation)"),

    _nt(85, "Oleamide", "OA", "GAS", "Modulatory",
        "Modulatory (enhances GABAergic/serotonergic transmission)",
        "Oleic Acid (amidation)",
        "Peptidylglycine Alpha-Amidating Monooxygenase (PAM)",
        "Widespread (CSF, Brain)",
        "GABA-A (positive modulator), 5-HT receptors, CB1 (weak)",
        "Sleep induction, gap junction modulation",
        "Insomnia, Sleep disorders",
        "FAAH inhibitors (oleamide is a FAAH substrate)"),

    _nt(86, "Palmitoylethanolamide", "PEA-lipid", "GAS", "Modulatory",
        "Modulatory (PPARalpha agonist, mast cell modulation, entourage effect on endocannabinoids)",
        "Palmitic Acid + Ethanolamine",
        "NAPE-PLD (same pathway as anandamide)",
        "Widespread (Peripheral and Central)",
        "PPARalpha (nuclear receptor), GPR55, GPR119, TRPV1 (indirect via entourage)",
        "Anti-inflammatory, pain modulation, neuroprotection",
        "Chronic pain, Neuroinflammation, Neuropathy, Fibromyalgia",
        "PEA supplements (Normast/Levagen), FAAH inhibitors"),

    _nt(87, "N-Arachidonoyl Dopamine", "NADA", "GAS", "Mixed",
        "Excitatory via TRPV1, inhibitory via CB1",
        "Arachidonic Acid + Dopamine",
        "FAAH (degradation), Conjugation enzymes (synthesis debated)",
        "Striatum, Hippocampus, Cerebellum",
        "TRPV1 (ionotropic cation channel), CB1 (Gi-coupled GPCR)",
        "Endovanilloid/endocannabinoid: pain modulation",
        "Chronic pain, Neuroinflammation",
        "TRPV1 antagonists (Capsazepine), CB1 ligands"),

    _nt(88, "Sulfur Dioxide", "SO2", "GAS", "Modulatory",
        "Modulatory (emerging gasotransmitter, modulates ion channels)",
        "L-Cysteine (via AAT enzyme)",
        "Aspartate Aminotransferase (AAT)",
        "Hypothalamus, Brainstem",
        "L-type Ca2+ channels, KATP channels (modulatory targets)",
        "Vasodilation, neuromodulation",
        "Hypertension, Vascular disease (emerging)",
        "SO2 donors (experimental), AAT modulators"),

    _nt(89, "Virodhamine", "Vir", "GAS", "Modulatory",
        "Modulatory (partial CB1 antagonist / CB2 agonist)",
        "Arachidonic Acid + Ethanolamine (O-linked)",
        "Unknown (non-enzymatic O-acyl formation proposed)",
        "Hippocampus, Periphery",
        "CB1 (partial antagonist), CB2 (full agonist) (GPCRs)",
        "Immune modulation, endocannabinoid tone regulation",
        "Inflammatory conditions, Immune disorders",
        "CB1/CB2 ligands, FAAH inhibitors"),

    _nt(90, "Lysophosphatidic Acid", "LPA", "GAS", "Excitatory",
        "Excitatory via LPA1-6 coupled to Gq/Gi/G12/13",
        "Membrane Phospholipids (via Autotaxin)",
        "Autotaxin (lysophospholipase D / ENPP2)",
        "Cortex, Hippocampus, Spinal Cord",
        "LPA1-6 (Gq, Gi, G12/13 coupled GPCRs)",
        "Neuropathic pain, myelination, neurodevelopment",
        "Neuropathic pain, Idiopathic pulmonary fibrosis, Spina bifida",
        "Autotaxin inhibitors (GLPG1690/Ziritaxestat), LPA1 antagonists (BMS-986020)"),

    # ===== ADDITIONAL NTs (IDs 91, 92-94 continued) =====
    _nt(91, "Agmatine", "Agm", "AA", "Inhibitory",
        "Inhibitory (NMDA antagonist, imidazoline receptor agonist)",
        "L-Arginine (decarboxylation via ADC)",
        "Arginine Decarboxylase (ADC)",
        "Hypothalamus, Hippocampus, Adrenal",
        "NMDA receptor (antagonist), Imidazoline I1/I2 receptors, Alpha-2 adrenergic, nAChR (blocker)",
        "NMDA antagonism, neuroprotection, antidepressant-like effects",
        "Depression, Neuropathic pain, Drug addiction, Stroke",
        "Agmatine supplements, Imidazoline receptor ligands"),

    _nt(92, "Acetaldehyde", "AcAld", "GAS", "Modulatory",
        "Modulatory (CNS depressant at low levels)",
        "Ethanol Metabolism (via ADH)",
        "Alcohol Dehydrogenase (ADH), Aldehyde Dehydrogenase (ALDH2 for degradation)",
        "Widespread (trace)",
        "GABA-A (potentiation), Opioid system (via salsolinol formation)",
        "CNS depression, addictive behavior modulation",
        "Alcoholism, Alcohol flushing syndrome (ALDH2 deficiency)",
        "Disulfiram (ALDH inhibitor, causes acetaldehyde buildup), Naltrexone (opioid antagonist for alcohol)"),

    _nt(93, "Prostaglandin E2", "PGE2", "GAS", "Excitatory",
        "Excitatory (EP1-4 receptors, sensitizes nociceptive neurons)",
        "Arachidonic Acid (via COX)",
        "Cyclooxygenase-1/2 (COX-1/COX-2), Prostaglandin E Synthase (mPGES)",
        "Hypothalamus, Spinal Cord",
        "EP1 (Gq), EP2 (Gs), EP3 (Gi), EP4 (Gs) (GPCRs)",
        "Fever, pain sensitization, neuroinflammation",
        "Fever, Inflammatory pain, Cancer, Neuroinflammation",
        "NSAIDs (Ibuprofen, Aspirin, Celecoxib - COX inhibitors), EP receptor antagonists"),

    _nt(94, "Prostaglandin D2", "PGD2", "GAS", "Modulatory",
        "Modulatory via DP1/DP2 receptors",
        "Arachidonic Acid (via COX/PGDS)",
        "Cyclooxygenase (COX-1/2), Prostaglandin D Synthase (L-PGDS, H-PGDS)",
        "Preoptic Area, Meninges",
        "DP1 (Gs, vasodilation/sleep), DP2/CRTH2 (Gi, immune) (GPCRs)",
        "Sleep promotion, allergic response",
        "Insomnia, Allergic rhinitis, Asthma, Mastocytosis",
        "DP2/CRTH2 antagonists (Fevipiprant), COX inhibitors (NSAIDs)"),

    # ===== NON-OPIOID PEPTIDES continued (IDs 95-100, 103-106, 108) =====
    _nt(95, "Nerve Growth Factor", "NGF", "NOP", "Modulatory",
        "Modulatory via TrkA receptor (tyrosine kinase)",
        "Pro-NGF",
        "Furin, Proprotein Convertases, Plasmin (extracellular cleavage)",
        "Basal Forebrain, Hippocampus",
        "TrkA (receptor tyrosine kinase), p75NTR (pan-neurotrophin receptor)",
        "Neuronal survival, pain sensitization, cholinergic support",
        "Alzheimer's disease, Chronic pain, Peripheral neuropathy",
        "Tanezumab, Fasinumab (anti-NGF mAbs), NGF eye drops (Cenegermin)"),

    _nt(96, "Brain-Derived Neurotrophic Factor", "BDNF", "NOP", "Modulatory",
        "Modulatory via TrkB receptor (tyrosine kinase)",
        "Pre-pro-BDNF",
        "Furin (intracellular), Plasmin, MMP-9 (extracellular pro-BDNF cleavage)",
        "Hippocampus, Cortex, VTA",
        "TrkB (receptor tyrosine kinase), p75NTR",
        "Synaptic plasticity, learning, memory, antidepressant effects",
        "Depression, PTSD, Alzheimer's disease, Huntington's disease",
        "Antidepressants (increase BDNF), Exercise (increases BDNF), Ketamine, 7,8-DHF (TrkB agonist)"),

    _nt(97, "Neurotrophin-3", "NT-3", "NOP", "Modulatory",
        "Modulatory via TrkC receptor (tyrosine kinase)",
        "Pre-pro-NT-3",
        "Furin, Proprotein Convertases",
        "Hippocampus, Cerebellum, PNS",
        "TrkC (receptor tyrosine kinase), p75NTR",
        "Neuronal differentiation, proprioception, synapse formation",
        "Peripheral neuropathy, Hearing loss, Neurodevelopmental disorders",
        "NT-3 protein (experimental gene therapy)"),

    _nt(98, "Neurotrophin-4/5", "NT-4/5", "NOP", "Modulatory",
        "Modulatory via TrkB receptor (tyrosine kinase)",
        "Pre-pro-NT-4/5",
        "Furin, Proprotein Convertases",
        "Motor Cortex, Striatum",
        "TrkB (receptor tyrosine kinase), p75NTR",
        "Motor neuron survival, synaptic modulation",
        "ALS, Motor neuron disease",
        "TrkB agonists (7,8-DHF), Neurotrophic factor therapies (experimental)"),

    _nt(99, "Glial Cell-Derived Neurotrophic Factor", "GDNF", "NOP", "Modulatory",
        "Modulatory via GFRalpha1/RET receptor complex",
        "Pre-pro-GDNF",
        "Furin, Proprotein Convertases",
        "Striatum, Substantia Nigra",
        "GFRalpha1/RET (receptor tyrosine kinase complex), GFRalpha2-4",
        "Dopaminergic neuron survival, neuroprotection (Parkinson's)",
        "Parkinson's disease, ALS, Addiction",
        "GDNF gene therapy (clinical trials), BT13 (RET agonist), Neurturin (GDNF family)"),

    _nt(100, "Neuregulin-1", "NRG1", "NOP", "Modulatory",
        "Modulatory via ErbB3/ErbB4 receptor tyrosine kinases",
        "NRG1 Gene",
        "BACE1 (beta-secretase, ectodomain shedding), ADAM10/17",
        "Cortex, Hippocampus",
        "ErbB4, ErbB3/ErbB2 heterodimer (receptor tyrosine kinases)",
        "Myelination, synaptic plasticity, schizophrenia susceptibility",
        "Schizophrenia, Bipolar disorder, Multiple sclerosis",
        "ErbB4 modulators (experimental), BACE1 inhibitors"),

    # ===== AMINO ACIDS continued (IDs 101, 102, 107) =====
    _nt(101, "Acetyl-L-Carnitine", "ALCAR", "AA", "Modulatory",
        "Modulatory (enhances cholinergic transmission and mGluR modulation)",
        "L-Carnitine (acetylation)",
        "Carnitine Acetyltransferase (CrAT)",
        "Mitochondria, Hippocampus",
        "mGluR2 (modulation), Nicotinic ACh receptors (enhancer), NGF pathway",
        "Neuroprotection, energy metabolism, antidepressant-like",
        "Depression, Neuropathy, Alzheimer's disease, Chronic fatigue",
        "ALCAR supplements, Levocarnitine"),

    _nt(102, "Zinc", "Zn2+", "AA", "Modulatory",
        "Modulatory (allosteric NMDA antagonist, AMPA/GABA modulator)",
        "Dietary intake / ZnT3 transporter",
        "ZnT3 (vesicular zinc transporter), ZIP transporters (uptake)",
        "Hippocampus (Mossy Fibers), Cortex",
        "NMDA receptor (allosteric inhibitor), AMPA/Kainate (modulator), GABA-A (modulator), GPR39",
        "Synaptic modulation, memory",
        "Depression, Epilepsy, Alzheimer's disease, Zinc deficiency cognitive impairment",
        "Zinc supplements, Clioquinol (zinc ionophore, Alzheimer's research)"),

    _nt(103, "Peptide YY", "PYY", "NOP", "Inhibitory",
        "Inhibitory via Y2 receptor coupled to Gi",
        "Pre-pro-PYY",
        "Prohormone Convertases, Dipeptidyl Peptidase IV (DPP-IV, generates PYY3-36)",
        "GI Tract, Brainstem (NTS)",
        "Y2 receptor (Gi-coupled GPCR, preferential), Y1, Y5",
        "Appetite suppression post-meal, energy balance",
        "Obesity, Bariatric surgery physiology, Eating disorders",
        "PYY3-36 analogs (experimental), DPP-IV inhibitors (sitagliptin)"),

    _nt(104, "Galanin-Like Peptide", "GALP", "NOP", "Modulatory",
        "Modulatory via galanin receptors",
        "Pre-pro-GALP",
        "Prohormone Convertases",
        "Hypothalamus (Arcuate)",
        "GalR1, GalR2, GalR3 (GPCRs)",
        "Feeding regulation, reproduction, thermoregulation",
        "Obesity, Reproductive disorders, Thermoregulatory dysfunction",
        "Galanin receptor agonists/antagonists (experimental)"),

    _nt(105, "Insulin", "INS", "NOP", "Modulatory",
        "Modulatory via Insulin Receptor tyrosine kinase",
        "Proinsulin",
        "Prohormone Convertases (PC1/PC3, PC2), Carboxypeptidase E",
        "Pancreas, Hypothalamus, Hippocampus",
        "Insulin Receptor (IR, receptor tyrosine kinase), IGF-1R",
        "Glucose regulation, synaptic plasticity, cognitive function",
        "Diabetes (Type 1/2), Alzheimer's disease (Type 3 diabetes hypothesis), Metabolic syndrome",
        "Insulin (Lispro, Glargine), Intranasal insulin (Alzheimer's research), Metformin (insulin sensitizer)"),

    _nt(106, "Leptin", "LEP", "NOP", "Modulatory",
        "Modulatory via LepR coupled to JAK-STAT pathway",
        "OB Gene",
        "OB gene expression in adipocytes (constitutive secretion)",
        "Adipose Tissue -> Hypothalamus (Arcuate)",
        "LepR / OB-R (Leptin receptor, JAK-STAT signaling)",
        "Satiety, energy expenditure, reward modulation",
        "Obesity (leptin resistance), Congenital leptin deficiency, Lipodystrophy",
        "Metreleptin (recombinant leptin), Leptin sensitizers (experimental)"),

    _nt(107, "D-Cycloserine analogue (endogenous D-serine)", "DCS-endo", "AA", "Excitatory",
        "Excitatory (NMDA partial agonist at glycine site)",
        "Serine metabolism",
        "Serine Racemase (SRR), D-Amino Acid Oxidase (DAAO, degradation)",
        "Cortex, Hippocampus",
        "NMDA receptor (glycine site partial agonist)",
        "NMDA receptor partial agonist, fear extinction",
        "PTSD, Anxiety disorders, Schizophrenia (negative symptoms)",
        "D-Cycloserine (augments exposure therapy), Sodium benzoate (DAAO inhibitor)"),

    _nt(108, "Gastric Inhibitory Polypeptide", "GIP", "NOP", "Modulatory",
        "Modulatory via GIPR coupled to Gs",
        "Pre-pro-GIP",
        "Prohormone Convertases, Signal Peptidase",
        "GI Tract, Hippocampus",
        "GIPR (Gs-coupled GPCR)",
        "Incretin effect, neuroprotection, cognitive modulation",
        "Type 2 Diabetes, Obesity, Cognitive decline",
        "Tirzepatide (dual GIP/GLP-1R agonist), DPP-IV inhibitors (Sitagliptin)"),
]
